### ISSUE TITLE
Headers missing

### ISSUE THREAD

**Issue by dimejo** [ruslandoga/bamboo_mua#53]
E-Mails send by this adapter (and used in Plausible) are flagged as spam by some providers, as some headers like `Date` and `Message-ID` are missing. Please see my [comment at the Plausible Discussions](https://github.com/plausible/analytics/discussions/3225) for a small explanation.

Unfortunately RFC 2822 and 5322 do not clearly comment on whos job it is to create these headers. But as some of the most used MTAs do not create missing headers by default they should be created by the client (MUA).

Further read:
https://en.wikipedia.org/wiki/Email#Header_fields
https://en.wikipedia.org/wiki/Message-ID

**Comment by ruslandoga** [comment]
👋 @dimejo 

Thank you for reminding me about this issue -- I completely forgot about it😅

I'll try to handle it in https://github.com/ruslandoga/bamboo_mua/pull/54

**Comment by dimejo** [comment]
Thanks for the fast PR!
